### ISSUE TITLE
Função de mascarar CPF

### ISSUE THREAD

**Issue by beatrizmilz** [gabrielacaesar/segurancaSP#13]
https://github.com/abjur/abjutils/issues/18

- Faz sentido nesse pacote? Se não, em qual poderia estar?

- Se sim, possibilidade de PR.

**Comment by gabrielacaesar** [comment]
Oi, @beatrizmilz! Nesse pacote acho que não se encaixa muito. Não sei onde entraria bem... Eu estava precisando disso para um cruzamento do trabalho. Achei que poderia estar em algum pacote jurídico ou em algum pacote ligado a dados públicos.
